# Generated by Django 4.2 on 2023-05-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0002_operario_estado_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='operario',
            name='email',
            field=models.EmailField(default=0.0004943153732081067, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operario',
            name='escalaSuplementos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='operario',
            name='factorRitmo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default=0.0004943153732081067, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=0.0004943153732081067, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('U', 'Usuario')], default='U', max_length=20),
        ),
        migrations.AlterField(
            model_name='operario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='operario',
            name='tiempoEstandar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
