# Generated by Django 4.2 on 2023-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0003_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionoperario',
            name='uniHoras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
