# Generated by Django 4.1.5 on 2023-07-11 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0003_operario_email_operario_escalasuplementos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
