# Generated by Django 4.1.5 on 2023-08-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0004_remove_usuario_edad_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
