# Generated by Django 4.2 on 2023-09-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0004_operacionoperario_unihoras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
