# Generated by Django 4.2 on 2023-10-31 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0005_alter_maquina_nombre_alter_operacion_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('nit', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='maquina',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cronometro.empresa'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cronometro.empresa'),
        ),
        migrations.AddField(
            model_name='operario',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cronometro.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cronometro.empresa'),
        ),
    ]
