# Generated by Django 4.1.5 on 2023-09-04 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0006_maquina_operacion_operacionoperario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operario',
            name='escalaSuplementos',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='factorRitmo',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='tiempoEstandar',
        ),
        migrations.AddField(
            model_name='operacionoperario',
            name='escalaSuplementos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='operacionoperario',
            name='factorRitmo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='operacionoperario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacionoperario',
            name='tiempoEstandar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
