# Generated by Django 4.2 on 2023-10-31 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0007_alter_maquina_empresa_alter_operacion_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='empresa',
            new_name='idEmpresa',
        ),
        migrations.RenameField(
            model_name='operacion',
            old_name='empresa',
            new_name='idEmpresa',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='empresa',
            new_name='idEmpresa',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='empresa',
            new_name='idEmpresa',
        ),
    ]
