# Generated by Django 4.2 on 2023-10-31 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0008_rename_empresa_maquina_idempresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='idEmpresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cronometro.empresa'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='idEmpresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cronometro.empresa'),
        ),
        migrations.AlterField(
            model_name='operacionoperario',
            name='idOperario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cronometro.operario'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='idEmpresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cronometro.empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idEmpresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cronometro.empresa'),
        ),
    ]
