# Generated by Django 4.2 on 2023-11-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0009_alter_maquina_idempresa_alter_operacion_idempresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operario',
            name='entidad',
        ),
    ]
