# Generated by Django 4.2 on 2023-11-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronometro', '0010_remove_operario_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
